spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/adminService
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        show_sql: false
        use_sql_comments: false
        format_sql: false
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    enableSelfPreservation: false
  cloud: 
    refresh: 
      enabled: false

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        iso lation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  eureka:
    enabled: true

