server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/client_service
    username: client_service
    password: client_service
    driverClassName: org.postgresql.Driver

  cloud: 
    refresh: 
      enabled: false


